# Generated by Django 3.0.8 on 2020-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('eGRID_subregion', models.CharField(max_length=4)),
                ('ced', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('state_FIPS', models.IntegerField()),
                ('county_FIPS', models.IntegerField()),
                ('county_name', models.CharField(max_length=50)),
                ('climate_zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EGRID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('eGRID_subregion', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
        migrations.CreateModel(
            name='Fastcharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watt', models.CharField(default='', max_length=120000)),
            ],
        ),
        migrations.CreateModel(
            name='GWP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('eGRID_subregion', models.CharField(max_length=4)),
                ('gwp', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='HomeESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.CharField(default='', max_length=6)),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
        migrations.CreateModel(
            name='MicrogridESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.CharField(default='', max_length=6)),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
        migrations.CreateModel(
            name='PVSoilingLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_zone', models.IntegerField(null=True)),
                ('loss_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TouMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
        migrations.CreateModel(
            name='ZipcodeCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('county_name', models.CharField(max_length=50)),
            ],
        ),
    ]
