# Generated by Django 3.0.8 on 2020-07-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricConsumption',
        ),
        migrations.DeleteModel(
            name='TouMatrix',
        ),
    ]
