# Generated by Django 3.0.8 on 2020-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200708_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
        migrations.CreateModel(
            name='TouMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
    ]
