# Generated by Django 3.0.8 on 2020-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_electricconsumption_toumatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_list', models.CharField(default='', max_length=120000)),
            ],
        ),
    ]
